### ISSUE TITLE
Index out of range warning

### ISSUE THREAD

**Issue by ReinerBforartists** [3ckSpeX/PrimitiveCreationModals#1]
Hi 3ckSpeX,

Blender 2.79a spits a Index out of range warning when i adjust the divisions in the last operator, and go accidentally into negative values. When you type in a positive value, then all works again. So i think you should implement a check to allow just positive values.

Kind regards

Reiner

![negativevals](https://user-images.githubusercontent.com/13919702/36971420-1274c9ca-206c-11e8-88fc-c6424d0971ee.jpg)
![errormessage](https://user-images.githubusercontent.com/13919702/36971424-16330b12-206c-11e8-8161-57a409b50660.jpg)

**Comment by 3ckSpeX** [comment]
Thanks for the heads up, made the fix.
