### ISSUE TITLE
Feature Request - Tooltips for the buttons

### ISSUE THREAD

**Issue by ReinerBforartists** [3ckSpeX/PrimitiveCreationModals#2]
Hi 3ckSpeX,

The buttons currently just shows the Python operators. A tooltip text would be neat to have. Tool name, what it does, how to use it.

Kind regards

Reiner

**Comment by 3ckSpeX** [comment]
I downloaded Bforartists to check, do you mean tool tips like that format where they have the name of the tool then, what it is? And do you mean only for the buttons in the tool panel or also the add menu and the redo options?

**Comment by ReinerBforartists** [comment]
I have just commited the version with your addon included before a few seconds. So not sure if you have the version where your addon is included already ^^

I mean the tooltips that you usually see when you hover over the buttons. It depends of course of how many information you really want to add here. I personally add as told tool name, what it does, and how to use it. So, for example:

Box Modal
Adds a box in Max style
Drag to draw the ground rectangle, click, drag to create the box height
Then adjust the subdivisions in the last operator

Line breaks in the tooltip can be done with the \n tag since i think Blender 2.78.

![tooltip](https://user-images.githubusercontent.com/13919702/37021840-3e16e6d4-2121-11e8-844c-d74e49ee5575.jpg)

**Comment by 3ckSpeX** [comment]
ok, I added tool tips for them and I think they have enough explanation for the basic use of the tool but there are a few hotkeys and things like that, that I wasn't sure how to explain to the user and right now that info is locked only in the read me. I was wondering if you know how to add the hotkeys for the modal to the bottom of the 3d view like they do for the bevel tool?

**Comment by ReinerBforartists** [comment]
Great :)

Yeah, help text in the header would be nice. But that's C code. Nothing that an addon developer could access. Well, you could prepend some text to the header ...

The better solution is imho to display a help text directly in the viewport. That way you have also more space. I do this with the Important Hotkey tool. Maybe with an addon preference prop so that more experienced users can turn the help text off in the addon setting.

See for example here for drawing a text: https://blender.stackexchange.com/questions/31770/draw-text-with-2-colors-in-viewport

**Comment by 3ckSpeX** [comment]
ok, I was hoping that it wasn't C, but it is so in that case I either have to make some sort of on screen help bar like you suggested, or make some sort of documentation so I can use that documentation link in the preferences and just hope that users will look at that. Anyway I take it that, that solves your request so I can close this thread right?

**Comment by ReinerBforartists** [comment]
Sure. This task is fulfilled :)
