### ISSUE TITLE
Tooltips should not end with a dot

### ISSUE THREAD

**Issue by ReinerBforartists** [3ckSpeX/PrimitiveCreationModals#3]
Just a very minor flaw which normal users wouldn't even notice. But tooltips should not end with a dot. A debug build moans about it, and throws a warning. Doesn't happen in a release build though. But in the tooltip you get two dots at the line ending.

Don't ask me why the Blender developers adds a dot here at all ^^

![tooltipwithdot](https://user-images.githubusercontent.com/13919702/37256245-3784652c-2558-11e8-9ce2-08b681640e0c.jpg)

![twodots](https://user-images.githubusercontent.com/13919702/37256262-57597806-2558-11e8-9697-1ba206f791f0.jpg)

**Comment by 3ckSpeX** [comment]
Deleted the period and finally fixed the shift + A menu while I was at it, I know the shift + A doesn't matter for bforartists but it was really bugging me.

**Comment by ReinerBforartists** [comment]
Perfect :)
